#!/bin/bash

#SBATCH --account=researchers
#SBATCH --job-name=sparsegpt_bloom560m    # Job name
#SBATCH --output=logs/R-%x.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=logs/R-%x.%j.err     # Error handling
#SBATCH --nodes=1                # Total number of nodes requested
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu               # Schedule a GPU
#SBATCH --time=0-24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the red or brown queue

#srun hostname

# module load Anaconda3
source activate torchenv

OUTFILE="logs/outfile560m.txt"
PRUNE_METHOD="sparsegpt"
SPARSITY_RATIO=0.5

(time python3 main.py \
 --model bigscience/bloom-560m \
 --prune_method $PRUNE_METHOD \
 --sparsity_ratio $SPARSITY_RATIO \
 --sparsity_type unstructured \
 --save_model pruned_models/bloom-560m/${PRUNE_METHOD}-${SPARSITY_RATIO} \
 --save pruned_modedls/bloom-560m/${PRUNE_METHOD}-${SPARSITY_RATIO}) 2>> $OUTFILE

echo "${PRUNE_METHOD} with sparsity ratio ${SPARSITY_RATIO} completed" >> $OUTFILE